export const SelectWorkTypes = {
    SELECT_FIRST_LEVEL_INDEX: 'SELECT_FIRST_LEVEL_INDEX',
    SELECT_SECOND_LEVEL_INDEX: 'SELECT_SECOND_LEVEL_INDEX',
    SELECT_THIRD_LEVEL_INDEX: 'SELECT_THIRD_LEVEL_INDEX',
    SELECT_FORTH_LEVEL_INDEX: 'SELECT_FORTH_LEVEL_INDEX'
}