export const FetchContractInfoTypes = {
    SET_CONTRACT: 'SET_CONTRACT',
    FETCH_CONTRACT_ADDRESS_START: 'FETCH_CONTRACT_ADDRESS_START',
    FETCH_CONTRACT_ADDRESS_SUCCESS: 'FETCH_CONTRACT_ADDRESS_SUCCESS',
    FETCH_CONTRACT_ADDRESS_FAILURE: 'FETCH_CONTRACT_ADDRESS_FAILURE'
}