export const SelectProjectTypes = {
    SELECT_PROJECT: 'SELECT_PROJECT',
    FETCH_PROJECT_WBS_START: 'FETCH_PROJECT_WBS_START',
    FETCH_PROJECT_WBS_SUCCESS: 'FETCH_PROJECT_WBS_SUCCESS',
    FETCH_PROJECT_WBS_FAILURE: 'FETCH_PROJECT_WBS_FAILURE'
}