export const FetchUserInfoTypes = {
    FETCH_ACCOUNT_START: 'FETCH_ACCOUNT_START',
    FETCH_ACCOUNT_SUCCESS: 'FETCH_ACCOUNT_SUCCESS',
    FETCH_ACCOUNT_FAILURE: 'FETCH_ACCOUNT_FAILURE',
    FETCH_NAME_START: 'FETCH_NAME_START',
    FETCH_NAME_SUCCESS: 'FETCH_NAME_SUCCESS',
    FETCH_NAME_FAILURE: 'FETCH_NAME_FAILURE',
    FETCH_COMPANY_START: 'FETCH_COMPANY_START',
    FETCH_COMPANY_SUCCESS: 'FETCH_COMPANY_SUCCESS',
    FETCH_COMPANY_FAILURE: 'FETCH_COMPANY_FAILURE'
}