export const FetchInspectionSheetTypes = {
    FETCH_INSPECTION_SHEET_START: 'FETCH_INSPECTION_SHEET_START',
    FETCH_INSPECTION_SHEET_SUCCESS: 'FETCH_INSPECTION_SHEET_SUCCESS',
    FETCH_INSPECTION_SHEET_FAILURE: 'FETCH_INSPECTION_SHEET_FAILURE'
}