export const FetchExecutingStateTypes = {
    FETCH_EXECUTING_STATE_START: 'FETCH_EXECUTING_STATE_START',
    FETCH_EXECUTING_STATE_SUCCESS: 'FETCH_EXECUTING_STATE_SUCESS',
    FETCH_EXECUTING_STATE_FAILURE: 'FETCH_EXECUTING_STATE_FAILURE'
}