export const FetchInspectionItemsTypes = {
    FETCH_INSPECTION_ITEMS_START: 'FETCH_INSPECTION_ITEMS_START',
    FETCH_INSPECTION_ITEMS_SUCCESS: 'FETCH_INSPECTION_ITEMS_SUCCESS',
    FETCH_INSPECTION_ITEMS_FAILURE: 'FETCH_INSPECTION_ITEMS_FAILURE'
}